### ISSUE TITLE
synchronous or asynchronous operation

### ISSUE THREAD

**Issue by dymczykm** [Sakura-IT/decelerator4030#4]
Hi, I'm digging a bit into 68030 accelerators for old compact Macs and came across your project, it's a really neat design and a good example of interfacing a CPU to the bus.

One question that I wanted to ask if - have your ever run decelerator asynchronously w.r.t. to the system bus? My system bus operates at 16 MHz, but I would like to have 68030 at a higher frequency. Looking (briefly) at your logic equations, it seems that so far you have only forwarded the bus signals to the CPU without taking care of differing frequencies, is that correct?

Pozdrawiam!

**Comment by rkujawa** [comment]
@dymczykm Correct, due to personal circumstances the project has been indefinitely delayed.

The original idea was to run the CPU asynchronously, however I have never got into that and the prototype (successfully) ran synchronously to the Amiga bus.

**Comment by dymczykm** [comment]
Thanks for the quick answer - I more or less know where I stand now. In any case, the decelerator project can serve me as a nice hardware reference, thanks a lot for making it open source! :+1: 

I'm not much acquainted with the Amiga world, but do you have maybe any good references regarding the asynchronous 68030 operation? I saw LUCAS and terriblefire accelerators do that for 68000->68030, I was curious if you know of logic description for 68030 or do I need to develop it from scratch.

Take care!

**Comment by rkujawa** [comment]
I am not aware of any open source designs that would interface to the 68030 bus. 

I think it boils down to the implementation details of the platform that you are targeting. In case of big box Amigas the local bus slot allows for both synchronous and asynchronous operation. It is even possible to drive the mainboard clocks from the CPU card. So in theory the logic on CPU board is only responsible for keeping the timings towards motherboard within limits (insert wait states where appropriate etc.). Unfortunately I don't remember details anymore. But I imagine in Macs it can be very different.

**Comment by dymczykm** [comment]
@rkujawa thanks for the explanation. So I think some reverse engineered Mac accelerators and a 68030 User's manual will be my friends :)

Indeed, this seems to be more complex in Macs. You basically need to glue all the bus control signals (such as DSACKx, AS, DS etc. ) manually to make sure slower devices can successfully exchange data on the bus.

Thanks in any case - already a hardware concept you're sharing will be of great help!

**Comment by rkujawa** [comment]
@dymczykm I guess this can be closed. Btw. If necessary you can always contact me using email address, as in commit messages of this repo.
